---
- name: install ntp
  apt: pkg=ntp state=present

- name: configure ntp to sync with controller
  template: >
    src="etc/ntp.conf.compute"
    dest="/etc/ntp.conf"
    owner="root"
    group="root"
    mode="0644"
  when: ntp_controller is defined

- name: start ntp
  service: name=ntp state=running enabled=yes

- name: set timezone
  template: >
    src=etc/timezone
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
  notify:
    - update debian timezone data
    - restart debian ntp service
