- host: localhost

- host: compute1
  vars:
    - compute_ip: "10.10.0.3"

- host: compute2
  vars:
    - compute_ip: "10.10.0.4"

- group: control
  hosts:
    - controller

- group: network
  hosts:
    - os-net

- group: compute
  hosts:
    - compute1
    - compute2

- group: openstack
  groups:
    - control
    - network
    - compute
