- host: localhost

- group: control
  hosts:
    - controller

- group: network
  hosts:
    - os-net

- group: compute
  hosts:
    - compute

- group: openstack
  groups:
    - control
    - network
    - compute
