---

- name: Create a service entry for the Identity Service
  command: "keystone service-create --name=keystone --type=identity --description='OpenStack Identity'"
  environment:
    OS_SERVICE_TOKEN: "{{ tokens.ADMIN }}"
    OS_SERVICE_ENDPOINT: "http://controller:35357/v2.0"

#endpointargs:
#  - "--service-id=$(keystone service-list | awk '/ identity / {print $2}') "
#  - "--publicurl=http://controller:5000/v2.0 "
#  - "--internalurl=http://controller:5000/v2.0 "
#  - "--adminurl=http://controller:35357/v2.0"

- name: Create a endpoint
  shell: "keystone endpoint-create --service-id=$(keystone service-list | awk '/ identity / {print $2}') --publicurl=http://controller:5000/v2.0 --internalurl=http://controller:5000/v2.0 --adminurl=http://controller:35357/v2.0"
  environment:
    OS_SERVICE_TOKEN: "{{ tokens.ADMIN }}"
    OS_SERVICE_ENDPOINT: "http://controller:35357/v2.0"
